# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daniel Silva
email: silva20102@gmail.com
description: "Blog para Compartilhamento de Informações"
baseurl: "/blog"
url: "http://danielsilva.net.br"
twitter_username: daniel10_silva
github_username:  silva01

# Build settings
markdown: kramdown
permalink: /:title/
